[phases.setup]
nixPkgs = ["...", "nodejs"]

[phases.install]
cmds = ["npm install --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build"]

[start]
run = "npm run preview -- --host 0.0.0.0 --port 4173"
